server:
  port: 8088

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    calculator-service:
      path: /calculator/**
      serviceId: calculator-service
      stripPrefix: true
    currency-service:
      path: /currency/**
      serviceId: currency-service
      stripPrefix: true

ribbon:
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout: 60000
