spring:
  application:
    name: calculator-service
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: test.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: test_kafka

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
